# Generated by Django 5.1 on 2024-09-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'verbose_name': 'Cook'},
        ),
        migrations.AddField(
            model_name='cook',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://www.twitter.com/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
