# Generated by Django 5.1 on 2024-09-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0002_alter_cook_options_cook_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cooks/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_time',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('DN', 'Dinner')], default='LN', max_length=2),
        ),
    ]
