# Generated by Django 5.1 on 2024-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0003_cook_photo_dish_image_dish_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(default='cooks/default.jpg', upload_to='cooks/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dishes/default.jpg', upload_to='dishes/'),
        ),
    ]
