# Generated by Django 5.1 on 2024-10-17 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0005_order_cook_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='The name field must contain only letters.', regex='^[A-Za-zА-Яа-яЁё]+$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
