# Generated by Django 5.1 on 2024-10-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0007_alter_cook_years_of_experience_alter_dish_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(default='cooks/default.jfif', upload_to='cooks/'),
        ),
    ]
