# Generated by Django 5.1 on 2024-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0009_alter_cook_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='is_cook',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a cook'),
        ),
    ]
