# Generated by Django 5.1 on 2024-10-31 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0010_cook_is_cook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Cooks and Customers'},
        ),
        migrations.AlterField(
            model_name='cook',
            name='facebook_link',
            field=models.URLField(default='https://www.facebook.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='cook',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='cook',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='cook',
            name='is_cook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cook',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='cook',
            name='twitter_link',
            field=models.URLField(default='https://www.twitter.com/', max_length=255),
        ),
    ]
