# Generated by Django 5.1 on 2024-11-05 02:45

import kitchen_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0011_alter_cook_options_alter_cook_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='facebook_link',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(default='cooks/default.jpg', upload_to=kitchen_service.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='cook',
            name='twitter_link',
            field=models.URLField(default='https://www.twitter.com/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
