# Generated by Django 5.1 on 2024-11-02 19:13

import kitchen_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0011_alter_cook_options_alter_cook_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(default='cooks/default.jpg', upload_to=kitchen_service.models.Cook.user_directory_path),
        ),
    ]
